apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gramps-web.fullname" . }}
  labels:
    {{- include "gramps-web.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "gramps-web.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "gramps-web.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "gramps-web.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: GRAMPSWEB_TREE
              value: {{ .Values.treeName }}
            - name: GRAMPSWEB_CELERY_CONFIG__broker_url
              value: redis://{{ include "gramps-web.redis.host" . }}:{{ include "gramps-web.redis.port" . }}/{{ include "gramps-web.redis.dbid" . }}
            - name: GRAMPSWEB_CELERY_CONFIG__result_backend
              value: redis://{{ include "gramps-web.redis.host" . }}:{{ include "gramps-web.redis.port" . }}/{{ include "gramps-web.redis.dbid" . }}
            - name: GRAMPSWEB_RATELIMIT_STORAGE_URI
              value: redis://{{ include "gramps-web.redis.host" . }}:{{ include "gramps-web.redis.port" . }}/{{ include "gramps-web.redis.dbid" . }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
          - name: data
            mountPath: /app/users
            subPath: users
          - name: data
            mountPath: /app/indexdir
            subPath: index
          - name: data
            mountPath: /app/thumbnail_cache
            subPath: thumb_cache
          - name: data
            mountPath: /app/cache
            subPath: cache
          - name: data
            mountPath: /app/secret
            subPath: secret
          - name: data
            mountPath: /root/.gramps/grampsdb
            subPath: grampsdb
          - name: data
            mountPath: /root/.gramps/media
            subPath: media
          - name: tmp
            mountPath: /tmp
          {{- if .Values.autoscaling.enabled }}
          {{- with .Values.volumes }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
      - name: data
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ if .Values.persistence.existingClaim }}{{ .Values.persistence.existingClaim }}{{- else }}{{ template "gramps-web.fullname" . }}-pvc{{- end }}
      {{- else }}
        emptyDir: {}
      {{- end }}
      - name: tmp
        emptyDir: {}
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
