{{- if .Values.config -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "focalboard.fullname" . }}
data:
  {{- with .Values.config }}
  serverRoot: {{ .serverRoot }}
  port: "{{ .port }}"
  config: |
    {{- toPrettyJson . | nindent 4 -}}
  {{- end }}
{{- end }}