{{- if .Values.customConfig.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cinny.fullname" . }}
data:
  {{- with .Values.customConfig.data }}
  config: |
    {{- toPrettyJson . | nindent 4 -}}
  {{- end }}
{{- end }}