{{- if .Values.persistence.enabled -}}
{{- if not .Values.persistence.existingClaim -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "unifi-controller.fullname" . }}-pvc
  labels:
    {{- include "unifi-controller.labels" . | nindent 4 }}
    # app.kubernetes.io/name: {{ include "unifi-controller.name" . }}
    # helm.sh/chart: {{ include "unifi-controller.chart" . }}
    # app.kubernetes.io/instance: {{ .Release.Name }}
    # app.kubernetes.io/managed-by: {{ .Release.Service }}
    # app.kubernetes.io/component: app
{{- if .Values.persistence.annotations }}
  annotations:
{{ toYaml .Values.persistence.annotations | indent 4 }}
{{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- if .Values.persistence.storageClass }}
{{- if (eq "-" .Values.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
{{- end }}
{{- end }}
{{- end -}}
{{- end -}}