# Default values for unifi-controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: lscr.io/linuxserver/unifi-network-application
  pullPolicy: IfNotPresent
  # -- Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

config:
  # -- Timezone - see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
  timezone: Etc/UTC
  jvmMemory:
    # -- Integer value in MB or `default` for startup memory for JVM
    startup: default
    # -- Integer value in MB or `default` for memory limit for JVM
    limit: default

persistence:
  enabled: false
  existingClaim: ""
  annotations: {}
  accessMode: ReadWriteOnce
  storageClass: ""
  size: 1Gi

serviceAccount:
  # -- Specifies whether a service account should be created
  create: true
  # -- Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use. If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  # -- Use the same service for TCP and UDP ports - set to disabled if using a LoadBalancer with MetalLB
  combinedProtocols: true
  annotations: {}

mongodb:
  # -- Deploy Bitnami MongoDB sub-chart
  enabled: true
  auth:
    rootUser: root
    rootPassword: unifi
    databases:
      - unifi
    usernames:
      - unifi
    passwords:
      - unifi
  initdbScriptsConfigMap: initdb-scripts

externalMongodb:
  # -- Use an external MongoDB database
  enabled: false
  # host: mongodb
  port: 27017
  database: unifi
  username: unifi
  # existingSecret: unifi-mongodb
  # existingSecretPasswordKey: password

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: unifi-controller.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: unifi-controller-tls
  #    hosts:
  #      - unifi-controller.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 400m
  #   memory: 1Gi
  # requests:
  #   cpu: 200m
  #   memory: 512Mi

nodeSelector: {}

tolerations: []

affinity: {}
