{{- if empty .Values.secretKey }}
apiVersion: v1
kind: Secret
metadata:
  name: "recipes-secret-key"
type: Opaque
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "recipes-secret-key") | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $secretKey := (get $secretData "recipes-secret-key") | default (randAlphaNum 64 | b64enc) }}
  password: {{ $secretKey | quote }}
{{- end }}